name: 'Setup Environment'
description: 'Sets up Python, Node.js, and uv, and optionally runs tests'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  run-tests:
    description: 'Whether to run tests after setup'
    required: false
    default: 'false'
  coverage:
    description: 'Whether to generate coverage report'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Run tests
      if: inputs.run-tests == 'true' && inputs.coverage != 'true'
      shell: bash
      run: uv run pytest

    - name: Generate coverage report
      if: inputs.run-tests == 'true' && inputs.coverage == 'true'
      shell: bash
      run: uv run pytest --cov=taskiq_kombu --cov-report=xml --cov-report=term-missing
